# This is an example mods.toml file for Forge. It controls mod loading data.
modLoader="javafml"
loaderVersion="${forge_loader_version_range}"

license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[mixins]]
config="endless_inventory.mixins.json"

[[dependencies."${mod_id}"]]
    modId="forge"
    type="required"
    versionRange="[${forge_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies."${mod_id}"]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies."${mod_id}"]]
    modId="jei"
    type="optional"
    mandatory=false
    versionRange="[19.5.0.59,)"
    ordering="AFTER"
    side="BOTH"
