buildscript {
    repositories {
        // These repositories are only for Gradle plugins, put any other repositories in the repository block further below
        maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
        mavenCentral()
    }
    dependencies {
        classpath 'org.spongepowered:mixingradle:0.7.38'
    }
}

plugins {
    id 'net.minecraftforge.gradle' version '6.+'
    id 'idea'
    id 'org.parchmentmc.librarian.forgegradle' version '1.+'
}

apply plugin: 'org.spongepowered.mixin'

base {
    archivesName = "${mod_name}-${project.name}-${minecraft_version}-${mod_version}"
}

mixin {
    add(sourceSets.main, "${mod_id}.refmap.json")

    config("${mod_id}.mixins.json")
    config("${mod_id}.experimental.mixins.json")
}

minecraft {
    mappings channel: "parchment", version: "${parchment_version}-${parchment_minecraft}"

    runs {
        client {
//            property 'mixin.env.remapRefMap', 'true'
//            property 'mixin.env.refMapRemappingFile', "${buildDir}/createSrgToMcp/output.srg"
        }
        data {
            workingDirectory project.file('run-data')

            // Specify the modid for data generation, where to output the resulting resource, and where to look for existing resources.
            args '--mod', mod_id, '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')
        }
        server {

        }
        configureEach {
            mods {
                "${mod_id}" {
                    source(sourceSets.main)
                    source(project(":common").sourceSets.main)
                }
            }
            jvmArg '--add-opens=java.base/java.lang.ref=ALL-UNNAMED'
        }
    }
}

sourceSets.main.resources.srcDir 'src/generated/resources'

repositories {
    maven { url = 'https://maven.parchmentmc.org' }
    mavenCentral()
    maven {
        // location of the maven that hosts JEI files before January 2023
        name = "Progwml6's maven"
        url = "https://dvs1.progwml6.com/files/maven/"
    }
    maven {
        // location of the maven that hosts JEI files since January 2023
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
    }
    maven {
        // location of a maven mirror for JEI files, as a fallback
        name = "ModMaven"
        url = "https://modmaven.dev"
    }
    maven {
        // Add curse maven to repositories
        name = "Curse Maven"
        url = "https://www.cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
    maven {
        name = "Curios"
        url = uri("https://maven.theillusivec4.top/")
    }
    maven {
        name = "Cloth Config"
        url = uri("https://maven.shedaniel.me/")
    }
}

dependencies {
    implementation project(":common")

    implementation 'org.jetbrains:annotations:24.0.1'

    annotationProcessor("org.spongepowered:mixin:0.8.7:processor")

    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"

    /* other minecraft dependencies are here */
    compileOnly("mezz.jei:jei-${minecraft_version}-forge-api:${jei_version}")
    // at runtime, use the full JEI jar for Forge
    implementation(fg.deobf("mezz.jei:jei-${minecraft_version}-forge:${jei_version}"))

    runtimeOnly fg.deobf("top.theillusivec4.curios:curios-forge:${curio_version}")
    compileOnly fg.deobf("top.theillusivec4.curios:curios-forge:${curio_version}:api")

    implementation fg.deobf("me.shedaniel.cloth:cloth-config-forge:${cloth_config_version}")
}

processResources {
    var expandProps = [
            'version'                      : mod_version,
            'group'                        : project.group, //Else we target the task's group.
            'minecraft_version'            : minecraft_version,
            'minecraft_version_range'      : minecraft_version_range,
            'fabric_version'               : fabric_version,
            'fabric_loader_version'        : fabric_loader_version,
            'mod_name'                     : mod_name,
            'mod_author'                   : mod_authors,
            'mod_id'                       : mod_id,
            'license'                      : mod_license,
            'description'                  : mod_description,
            "forge_version"                :        forge_version,
            "forge_loader_version_range"   : forge_loader_version_range,
            'credits'                      : credits,
            'java_version'                 : java_version
    ]

    var jsonExpandProps = expandProps.collectEntries {
        key, value -> [(key): value instanceof String ? value.replace("\n", "\\\\n") : value]
    }

    filesMatching(['META-INF/mods.toml']) {
        expand expandProps
    }

    filesMatching(['pack.mcmeta', 'fabric.mod.json', '*.mixins.json']) {
        expand jsonExpandProps
    }

    inputs.properties(expandProps)
}


jar {
    finalizedBy('reobfJar')
    from(project(':common').sourceSets.main.output)
    manifest.attributes([
            "MixinConfigs": "${mod_id}.mixins.json,${mod_id}.experimental.mixins.json"
    ])
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}
