@MethodsReturnNonnullByDefault@ParametersAreNonnullByDefault
package com.kwwsyk.endinv.neoforge;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;